# PyTorch Tutorial

## What is PyTorch?
PyTorch is an **open-source deep learning framework** developed by Facebook AI Research (FAIR). It provides dynamic computation graphs, easy debugging, and a **Pythonic** interface, making it an ideal choice for both researchers and practitioners.

### **Key Features of PyTorch:**
- **Tensors**: Multi-dimensional arrays similar to NumPy but with GPU acceleration.
- **Autograd**: Automatic differentiation for computing gradients.
- **Neural Networks (torch.nn)**: A module for building deep learning models.
- **Optimizers (torch.optim)**: Algorithms like SGD, Adam for model training.
- **Dataset and DataLoader**: Tools for handling data efficiently.
- **GPU Acceleration**: Seamless transition between CPU and GPU computations.

## 1. Installation and Setup

Install PyTorch using pip (or conda):

```bash
pip install torch torchvision
```

In [18]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

PyTorch version: 2.6.0+cu126
CUDA available: True


### Exercise 1

- Verify your installation by printing the computation device (CPU/GPU).

## 2. PyTorch Tensor Basics

### **Understanding PyTorch Tensors**

Tensors are the **building blocks of PyTorch**. They are similar to NumPy arrays but can run on **GPUs**.

**Common Tensor Operations:**
- Creating Tensors: `torch.tensor()`, `torch.zeros()`, `torch.ones()`, `torch.rand()`
- Reshaping: `tensor.view()` or `tensor.reshape()`
- Mathematical Operations: `+`, `-`, `*`, `matmul()`, etc.


### 1. Creating Tensors

Below are different ways to create tensors in PyTorch:
- `torch.tensor()` - Creates a tensor with specific values.
- `torch.zeros()` - Creates a tensor filled with zeros.
- `torch.ones()` - Creates a tensor filled with ones.
- `torch.rand()` - Creates a tensor with random values.

### Exercise:


In [19]:
print("\nCreating Tensors:")
# TODO: Create a tensor with values [1, 2, 3, 4] and print its shape.
# TODO: Create a tensor of shape (2,2) filled with zeros.
# TODO: Create a tensor of shape (3,3) filled with ones.
# TODO: Generate a random tensor of shape (2,3) and print its values.
tensor1 = torch.tensor([1,2,3,4])
tensor2 = torch.zeros(2,2)
tensor3 = torch.ones(3,3)
tensor4 = torch.rand(2,3)
print("Tensor 1:", tensor1.shape)
print("Tensor 2 (Zeros):", tensor2)
print("Tensor 3 (Ones):", tensor3)
print("Tensor 4 (Random):", tensor4)


Creating Tensors:
Tensor 1: torch.Size([4])
Tensor 2 (Zeros): tensor([[0., 0.],
        [0., 0.]])
Tensor 3 (Ones): tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Tensor 4 (Random): tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411]])


### 2. Tensor Attributes
Each tensor has attributes such as shape, data type, and device.

The **shape** of a tensor represents its dimensions (number of rows and columns, or more in higher-dimensional tensors).

Every tensor has a **data type** that defines the type of values it holds.
PyTorch supports different data types like *torch.float32, torch.int64, torch.bool*, etc. The default data type in PyTorch is **torch.float32**.

Tensors can be stored either on the CPU or GPU.

In [20]:
print("\nTensor Attributes:")
# TODO: Print tensor1 shape
# TODO: Print tensor1 data type
# TODO: Change tensor1 to other data type
# TODO: Print tensor1 device
# TODO: Move tensor1 to GPU (if available)
print(tensor1.shape)
print(tensor1.type())
print(tensor1.float())
print(tensor1.device)
print(torch.cuda.is_available())
device  = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tensor1 = tensor1.to(device)
print(tensor1.device)



Tensor Attributes:
torch.Size([4])
torch.LongTensor
tensor([1., 2., 3., 4.])
cpu
True
cuda:0


### 3. Tensor Operations
Tensors support mathematical operations such as addition, multiplication, and matrix multiplication.

In [21]:
print("\nTensor Operations:")
# TODO: Add tensor1 to itself and store the result
# TODO: Multiply tensor1 with itself and store the result
# TODO: Perform matrix multiplication on tensor1 with itself and store the result
# TODO: Print the results for addition, multiplication, and matrix multiplication
tensor_d = tensor1 + tensor1
tensor_mul = tensor1*tensor1
tensor1_2d = tensor1.view(4,1).to(torch.float32)
tensor_matmul = torch.matmul(tensor1_2d, tensor1_2d.T)
print(tensor_d)
print(tensor_mul)
print(tensor_matmul)



Tensor Operations:
tensor([2, 4, 6, 8], device='cuda:0')
tensor([ 1,  4,  9, 16], device='cuda:0')
tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  4.,  6.,  8.],
        [ 3.,  6.,  9., 12.],
        [ 4.,  8., 12., 16.]], device='cuda:0')


### 4. Reshaping Tensors
Reshaping tensors is important for data manipulation in machine learning.

In [22]:
print("\nReshaping Tensors:")
# TODO: Create a tensor with values from 1 to 9 using torch.arange
tensor5 = torch.arange(1,10)
# TODO: Reshape and print the tensor into a 3x3 matrix
tensor5 = tensor5.view(3,3)
print(tensor5)
# TODO: Reshape the tensor into (1x9) and print it
tensor5 = tensor5.view(9,1)
print(tensor5)
# TODO: Reshape the tensor into (9x1) and print it
tensor5 = tensor5.view(1,9)
print(tensor5)




Reshaping Tensors:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])


### 5. Exercises

Use other methods to create tensor in PyTorch

*torch.linspace(start, end, step)* is a function in PyTorch that creates a 1D tensor with  evenly spaced values between a specified start and end.

*torch.arange(start, end, step)* creates a 1D tensor with a specific step size between values.

*torch.full(size, fill_value)* creates a tensor filled with a specific value.

*torch.eye(n)* creates an identity matrix with 1s on the diagonal.

*torch.diag(tensor)* creates a diagonal matrix with elements of a given tensor along the diagonal.


In [23]:
# TODO: Create your own tensors using different methods in PyTorch.

tensor1 = torch.linspace(1, 10, 5)
print(tensor1)

tensor2 = torch.arange(1, 10, 2)
print(tensor2)

tensor3 = torch.full((3, 3), 7)
print(tensor3)

tensor4 = torch.eye(4)
print(tensor4)

tensor5 = torch.diag(torch.tensor([1, 2, 3, 4]))
print(tensor5)


tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
tensor([1, 3, 5, 7, 9])
tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])


## 3. PyTorch Autograd Basics

### **Understanding Autograd (Automatic Differentiation)**

PyTorch’s **autograd** module enables automatic differentiation, essential for **backpropagation**.

**Key Concepts:**
- `requires_grad=True`: Enables tracking gradients for a tensor.
- `tensor.backward()`: Computes the gradient w.r.t. tensor.
- `tensor.grad`: Accesses the computed gradient.


### 1. Introduction to Autograd

PyTorch's `autograd` package provides automatic differentiation for all operations on Tensors. It is a crucial tool for training neural networks.

In [24]:
import torch

# Enable autograd for computations
torch.manual_seed(42)

### 2. Creating Tensors with Gradient Tracking
To enable gradient tracking, set `requires_grad=True` when creating a tensor.

In [25]:
# TODO: Create a tensor with values [1, 2, 3, 4] and print its shape.
x = torch.tensor([[1,2,3,4]],dtype=torch.float32, requires_grad=True)
print(f'Tensor: {x}')

Tensor: tensor([[1., 2., 3., 4.]], requires_grad=True)


### 3. Performing Operations
Performing mathematical operations on tensors that have `requires_grad=True` automatically tracks these operations in the computation graph.

In [26]:
y = x**2 + 3*x + 5
print(f'Result: {y}')

Result: tensor([[ 9., 15., 23., 33.]], grad_fn=<AddBackward0>)


### 4. Computing Gradients
We compute the gradient of `y` with respect to `x` using `y.backward()`.

In [27]:
# TODO compute the gradient of y with respect to x using y.backward()
y.sum().backward()
print(f'Gradient of y with respect to x: {x.grad}')

Gradient of y with respect to x: tensor([[ 5.,  7.,  9., 11.]])


### 5. Disabling Gradient Tracking
For inference (when we don't need gradients), we can disable autograd tracking using `torch.no_grad()`.

In [28]:
# TODO: Create a function that disables gradient tracking using `torch.no_grad()`
def disable_grad(x):
    with torch.no_grad():
        x = x + 1  
    return x

### 6. Exercises
Try modifying the equation `y = x**2 + 3*x + 5` and compute gradients for different functions.

In [29]:
# TODO: Modify the equation y = x**2 + 3*x + 5 to a different function (example: y = x**3 + 2*x**2 + 4*x + 1) and compute its gradients.

y = x**3 + 2*x**2 + 4*x + 1
x.grad.zero_()
y.sum().backward()
print(x.grad)

tensor([[11., 24., 43., 68.]])


## 4. Data Handling and Preprocessing

### 1. Using Built-in Datasets and DataLoaders

Example: Loading the MNIST dataset using torchvision.

In [30]:
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.Compose([transforms.ToTensor()])

train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)

images, labels = next(iter(train_loader))
print("Batch shape:", images.shape, labels.shape)

Batch shape: torch.Size([64, 1, 28, 28]) torch.Size([64])


### 2. Creating Custom Datasets

Create your own dataset by subclassing `torch.utils.data.Dataset`.

In [31]:
from torch.utils.data import Dataset
from PIL import Image
import os

class CustomImageDataset(Dataset):
    def __init__(self, image_dir, transform=None):
        self.image_dir = image_dir
        self.transform = transform
        self.image_files = [f for f in os.listdir(image_dir) if f.endswith('.jpg') or f.endswith('.png')]

    def __len__(self):
        return len(self.image_files)

    def __getitem__(self, idx):
        img_path = os.path.join(self.image_dir, self.image_files[idx])
        image = Image.open(img_path)
        if self.transform:
            image = self.transform(image)
        return image

# Example usage:
# transform = transforms.Compose([transforms.Resize((128, 128)), transforms.ToTensor()])
# dataset = CustomImageDataset('path_to_images', transform=transform)
# loader = DataLoader(dataset, batch_size=32, shuffle=True)

### Exercise

- Write and test a custom dataset class that loads images from a directory.
- Apply normalization and other transformations.
- Use DataLoader to iterate over the dataset.

In [32]:
from torch.utils.data import Dataset
from PIL import Image
import os

class CustomImageDataset(Dataset):
    def __init__(self, image_dir, transform=None):
        self.image_dir = image_dir
        self.transform = transform
        self.image_files = [f for f in os.listdir(image_dir) if f.endswith('.jpg') or f.endswith('.png')]

    def __len__(self):
        return len(self.image_files)

    def __getitem__(self, idx):
        img_path = os.path.join(self.image_dir, self.image_files[idx])
        image = Image.open(img_path)
        if self.transform:
            image = self.transform(image)
        return image

# Example usage:
# transform = transforms.Compose([transforms.Resize((128, 128)), transforms.ToTensor()])
# dataset = CustomImageDataset('path_to_images', transform=transform)
# loader = DataLoader(dataset, batch_size=32, shuffle=True)

## 5. Building Neural Networks

### 1. The `nn.Module` Class

Create a simple neural network by subclassing `nn.Module`.

In [33]:
# TODO: Create a class `SimpleNN` that inherits from `nn.Module`
# TODO: Define an __init__ method to initialize two linear layers and a ReLU activation
# TODO: Implement the forward method that applies linear -> ReLU -> linear transformation
# TODO: Instantiate the model and print its architecture

import torch.nn as nn
class SimpleNN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(SimpleNN, self).__init__()
        self.linear1 = nn.Linear(input_dim, hidden_dim)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_dim, output_dim)
        
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        return out
        
        
model = SimpleNN(2,1,1)
print(model.type)

<bound method Module.type of SimpleNN(
  (linear1): Linear(in_features=2, out_features=1, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=1, out_features=1, bias=True)
)>


### 2. Forward Pass and Loss Calculation
We create dummy data and pass it through the model to compute the loss.

In [34]:
# TODO: Create a tensor `x_train` with shape (4,1) containing input values (1,2,3,4)
# TODO: Create a tensor `y_train` with shape (4,1) containing target values (2,4,6,8)
# TODO: Define the Mean Squared Error (MSE) loss function
# TODO: Perform a forward pass by passing `x_train` through the model to get predictions
# TODO: Compute the loss between predictions and `y_train`
# TODO: Print the initial loss value
x_train = torch.tensor([[1],[2],[3],[4]], dtype=torch.float32)
y_train = torch.tensor([[2],[4],[6],[8]], dtype=torch.float32)
criterion = nn.MSELoss()
model = SimpleNN(1,1,1)
y_pred = model(x_train)
loss = criterion(y_pred, y_train)
print(loss)

tensor(23.1419, grad_fn=<MseLossBackward0>)


### 3. Backward Pass and Gradient Calculation
We perform backpropagation by calling `loss.backward()` and inspect the gradients.

In [35]:
# TODO: Call backward() to compute gradients, then print them.
loss.backward()
for name, param in model.named_parameters():
    print(f'{name}: {param.grad}')

linear1.weight: tensor([[-0.1156]])
linear1.bias: tensor([-0.1156])
linear2.weight: tensor([[-0.0838]])
linear2.bias: tensor([-8.5097])


### 4. Updating Parameters with Optimization
We use Stochastic Gradient Descent (SGD) to update the model parameters.

In [36]:
from torch import optim
optimizer = optim.SGD(model.parameters(), lr=0.1)
# TODO: Apply an optimizer step and check parameter updates.
optimizer.step()
for name, param in model.named_parameters():
    print(f'{name}: {param}')
    

linear1.weight: Parameter containing:
tensor([[-0.7221]], requires_grad=True)
linear1.bias: Parameter containing:
tensor([0.8808], requires_grad=True)
linear2.weight: Parameter containing:
tensor([[0.1955]], requires_grad=True)
linear2.bias: Parameter containing:
tensor([1.5898], requires_grad=True)


### 5. Training Loop
We train the model for multiple epochs, performing forward and backward passes, and updating parameters.

In [37]:
epochs = 100
for epoch in range(epochs):
    optimizer.zero_grad()
    y_pred = model(x_train)
    loss = criterion(y_pred, y_train)
    loss.backward()
    optimizer.step()
    if (epoch) % 10 == 0:
        print(f'epoch:{epoch}, loss:{loss}')
    # TODO: Perform a forward pass and compute loss
    # TODO: Reset gradients, perform backpropagation, and update model parameters
    # TODO: Print loss every 10 epochs

epoch:0, loss:16.62348747253418
epoch:10, loss:5.135692596435547
epoch:20, loss:5.001564025878906
epoch:30, loss:5.000018119812012
epoch:40, loss:5.0
epoch:50, loss:5.0
epoch:60, loss:5.0
epoch:70, loss:5.0
epoch:80, loss:5.0
epoch:90, loss:5.0


### Exercise

- Build a neural network for binary classification using a synthetic dataset.
- Write a training loop and plot the loss curve over epochs.

## 6. Model Deployment

### 1. Saving and Loading Models

Save your trained model and load it later for inference.

In [39]:
# Saving the model
torch.save(model.state_dict(), "model.pth")

# Loading the model
model_loaded = SimpleNN(input_dim=1, hidden_dim=1, output_dim=1)
model_loaded.load_state_dict(torch.load("model.pth"))
model_loaded.eval()

SimpleNN(
  (linear1): Linear(in_features=1, out_features=1, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=1, out_features=1, bias=True)
)

### 2. Exporting with TorchScript

Convert your model to TorchScript for optimized production deployment.

In [40]:
scripted_model = torch.jit.script(model)
scripted_model.save("scripted_model.pt")

### Exercise

- Export a trained model using TorchScript or ONNX.
- Build a simple API (using Flask or FastAPI) that loads the model and returns predictions for a given input.

# important !
run terminal   
python app.py  
separate terminal  
curl -X POST -H "Content-Type: application/json" -d '{"input": [1.0]}' http://127.0.0.1:5001/predict

In [42]:
from flask import Flask, request, jsonify
app = Flask(__name__)

model = torch.jit.load("scripted_model.pt")
model.eval()

@app.route('/predict', methods=['POST'])
def predict():
    data = request.get_json()
    input_tensor = torch.tensor(data['input'], dtype=torch.float32).reshape(-1,1)
    with torch.no_grad():
        prediction = model(input_tensor).item()
    return jsonify({'pridiction': prediction})

In [43]:
app.run(debug=True)

 * Serving Flask app '__main__'
 * Debug mode: on


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
Traceback (most recent call last):
  File "/home/ir739wb/miniconda3/envs/myenv/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ir739wb/miniconda3/envs/myenv/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/ir739wb/miniconda3/envs/myenv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/home/ir739wb/miniconda3/envs/myenv/lib/python3.12/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/home/ir739wb/miniconda3/envs/myenv/lib/python3.12/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ir739wb/miniconda3/envs/myenv/lib/pyt

SystemExit: 1

/home/ir739wb/miniconda3/envs/myenv/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


## 7. Final Project and Conclusion

### 1. Final Project: Zadanie c.2

### 2. Conclusion and Further Resources

- **Recap:** This notebook has guided you from the basics of PyTorch to building and deploying a neural network.
- **Further Reading:**
  - [Official PyTorch Tutorials](https://pytorch.org/tutorials/)
  - [PyTorch Documentation](https://pytorch.org/docs/stable/index.html)
  - [Deep Learning with PyTorch: A 60 Minute Blitz](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)
  - [PyTorch Beginner Tutorial](https://www.youtube.com/watch?v=EMXfZB8FVUA&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4)